# -------------------------------------------------
# BakVakum Backend Development
# -------------------------------------------------

FROM node:22-alpine

LABEL maintainer="BakVakum Development"

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]